server:
  port: 8870

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/NeedLoser/config-server      # 配置git仓库的地址
          username:                                                 # git仓库的账号
          password:                                                 # git仓库的密码

# 注册中心配置
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/